apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: automated-vehicle-damage
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      containers:      - image: gcr.io/accidentdetector/automated-vehicle-damage
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REACT_APP_API_URL
          value: "https://automated-vehicle-damage-accidentdetector.europe-west1.run.app"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
