version: '3.8'

services:
  # Unified Flask App with React Frontend
  app:
    build: 
      context: .
      dockerfile: Dockerfile.unified
    container_name: vehicle-damage-app
    ports:
      - "5000:5000"
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/processed:/app/data/processed
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONPATH=/app
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: vehicle-damage-network
